apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentflow

resources:
  - namespace.yaml
  - configmap.yaml
  - agent-http-deployment.yaml
  - agent-http-service.yaml

images:
  - name: agentflow-go
    newName: ghcr.io/aijustin/agentflow-go
    newTag: latest