replicaCount: 1

image:
  repository: ghcr.io/aijustin/agentflow-go
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 18080

worker:
  enabled: true
  replicaCount: 1

server:
  enabled: true
  port: 18081

resources: {}
